language: perl
perl:
- '5.24'
before_install:
- git clone --depth=1 https://github.com/hknutzen/Netspoc.git ~/Netspoc
- export PERL5LIB=~/Netspoc/lib/
- sudo apt update -y
- sudo apt install apache2 -y
- sudo apt install rcs -y
- sudo systemctl start apache2
install:
- cpanm --notest CGI::Session
- cpanm --notest Crypt::SaltedHash
- cpanm --notest Digest::MD5
- cpanm --notest Digest::SHA
- cpanm --notest Encode
- cpanm --notest File::Path
- cpanm --notest File::Spec
- cpanm --notest Getopt::Long
- cpanm --notest HTML::Strip
- cpanm --notest IPC::Run3
- cpanm --notest JSON::XS
- cpanm --notest List::Util
- cpanm --notest Net::LDAP
- cpanm --notest NetAddr::IP::Util
- cpanm --notest parent
- cpanm --notest Plack::Test::Server
- cpanm --notest Plack::Middleware::XForwardedFor
- cpanm --notest Regexp::IPv6
- cpanm --notest String::MkPasswd
- cpanm --notest Template
- cpanm --notest Test::Selenium::Remote::Driver
- cpanm --notest Test::More
- cpanm --notest Test::Differences
- cpanm --notest Text::Template
- cpanm --notest Time::HiRes
- cpanm --notest XML::XPath
- cpanm --notest Cpanel::JSON::XS
- cpanm --notest Selenium::Remote::Driver
- cpanm --notest Sereal::Encoder

addons:
  browserstack:
    username: "heinzknutzen1"
    access_key:
      secure: Um0VRrukinnLDGeoR8ltLtMVBZg6LAeJ6LSnVoRFMO4SsVlNoqY+cCdiqVRx3uHvMwT4EOJVyhqoB8bbEsHkynYgBqR1U/IehU5zFU4PslDt8ifvtqjrqyUpmxWWLAUMUhOrxFyHid9+/G9JD05ojaPgKoCFIVKCWYBzEBGoBBnVbkLA3t6hhbUyOFIiwVe+haHXbacbXo26zDcLnzTmV775DsEgH10W8i6MA/HXpIfAJ+ToL0VpzbX16DIw+hlbNAQfftUiZ/QbF+hm6YEDQo9dB9E6GBBx9TDjCEqgUVgfNJc3j5U/zvHCQncz9Og7dUnndF4bVAPJ9NFZIgEB8b2vUTaYJqEH5iYZj7zPAjyNA81WYkUNc7yRPrR6e+6BLAS8T5B5p/oaEyTXulowJM7Zpx2J6a0MEpSyXQIcehgZ5h9dTkjqlj0YzmXid4Sx32kdJ1rp9i2XJ7tQBMGFRy4yWgBXp2VkkEqFZPU+im25TqhmUB0e29u+M2ukwJyOAX8Bnu5NfNE1GTCtfFo5xo2XnTuTux/yJl+0JYPG2DJl98Hhwc8JvtP+Yf//zeU6v0IHIg/uwqbZuJdVq/Wq3Mklx8QGWA1QBfV+oSyw6+DLKQ025LaOw5Evfz+6EHQmECdp3QX1s3GI1mHjPfTNBaigqckSNzj0mYSvzPflKVc=