#!/bin/sh
BASE=/home/netspocweb/NetspocWeb/bin
IP=127.0.0.1
PORT=5000
WORKER=5
USER=netspocweb
PIDFILE=/var/run/netspocweb/netspoc.pid

case $1 in
  start)
        starman \
            -l $IP:$PORT \
            -D \
            --pid $PIDFILE \
            --workers $WORKER \
            --user $USER \
            $BASE/netspoc.psgi
	;;
  reload)
	kill -HUP $(cat $PIDFILE)
	;;
  restart)
	$0 start
	$0 stop
	;;
  stop)
	kill $(cat $PIDFILE)
	rm -f $PIDFILE
	;;
  *)
	echo "Usage: $0{start|reload|restart|stop}"
	exit 1
	;;
esac
